name: FizzBuzz documentation
markdown: redcarpet
highlighter: pygments
baseurl: /cats
apidocs: /cats/api/
sources: https://github.com/denisrosset/checked-doc-template/blob/master

collections:
  tut:
    output: true
